ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT] image:https://img.shields.io/badge/View%20on-GitHub-orange[View on GitHub, link=https://github.com/goldfishlaser/tech-writer-resume] image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=https://goldfishlaser.github.io/tech-writer-resume/melanie-allen-resume.pdf]
endif::[]

== Melanie Allen

[%hardbreaks]
Technical Content Specialist
404-468-1620
melanienallen@gmail.com
Portfolio: https://mnallen.online

Dynamic communications professional with proven ability to develop diverse content for multiple industries. My passion is helping people gain knowledge and complete tasks with audience-centered design and copy.

=== Skill Summary

[%hardbreaks]
- Technical Communication: Information Design, Software Documentation, Installation Manuals, Instructional Design, Graphic Design, Documentation Lifecycle, SME Interviews
- Product Marketing: Research, Analytics, Marketing Copywriting and SEO, GTM Strategy
- Business: Security and Compliance, Remote Team Collaboration, Public Speaking, B2B

.Tool Proficiency
--
Git, Markdown, ASCIIDOC, HTML, CSS, JS, CMS, YAML, GIMP, Inkscape, OpenSCAD, LibreOffice, Adobe Creative Suite, Microsoft Office, Canva, Jira, Confluence
--

=== Professional Experience

==== Movius

.Product Marketing | March 2020 – March 2025
--
- Directly contributed to the success of product launches and product adoption by the customer by delivering quality  product marketing and end-user documentation.
- Managed the MultiLine Help Center in knowledge base software
- Wrote blogs using SEO techniques in Wordpress
- Collaborated with product, marketing, and sales team on positioning and messaging
- Created sales enablement materials in content management software
- Assisted with planning marketing events
--

==== US Tech Solutions

.Technical Writer | March 2018 – March 2020
--
- My work helped call center agents solve customer problems faster and with less friction, leading to higher CSAM scores and better customer experiences.
- Collaborated with the Fiber Education Team to maintain the Customer Service Knowledge Base for Google Fiber
- Scoped change impacts across documentation types.
- Participated in a complete revamping of the organization of our reusable content.
- Bootstrapped the new Sales knowledge base with materials from the CSR knowledge base.
- Used SEO techniques to optimize retrieval of information for techs on the job.
--

==== TOTO USA

.Technical Writer | April 2010 – October 2016
--
- My work directly improved both the consistency and accuracy of instructions and the quality of translations, resulting in reduced manual reprints because of errors and customer service calls. 
- Managed, edited, and created new installation manuals using InDesign and spare part sheets using Adobe Illustrator for the entire offering of plumbing fixtures and accessories at TOTO USA.
- Interviewed Product Engineers and Tech Support, participated in installation demonstrations, and reviewed existing documentation to gather information to write new installation manuals and spare part sheets with minimal oversight.
- Completed projects on schedule according to the Design Review (DR) and Modification Design Review (MDR) processes.
- Collaborated with the Documentation Specialist and Development Engineering team to complete edits to manuals and spare part sheets according to Engineering Change Notices (ECNs).
- Updated information for spare part sheets for China team in their Microsoft Access database.
- Created a Development Engineering Style Guide to ensure that documents were consistent in style, terminology, and layout.
--

==== Southern Polytechnic State University

.Instructional Designer | Aug 2012 – Aug 2013
--
- My efforts contributed towards the availability of more high quality hybrid learning opportunites for students at the university and less manual work by the Instrutional Design team to help instructors create their courses. 
- Worked on a team creating offline help documentation and material for workshops that taught SPSU faculty how to transition their online and face to face courses to the Desire2Learn LMS system.
- Helped with the development of a new Teaching Academy for Distance Learning course that provided "online teaching concepts, pedagogy, tools training [including GeorgiaVIEW Desire2Learn (D2L), Wimba, Respondus, Turnitin, Ensemble, etc.] and individualized assistance with course development/revision".
--

=== Education

*Southern Polytechnic State University* | 2012 | B.S. Technical Communication

*Rockdale Magnet School* | 2007 | Graduated with honors

=== Certifications

*DeepLearning.Ai via Coursera* | 2019 | Neural Networks and Deep Learning and Coursera

*Product Marketing Alliance* | 2023 | Product Marketing Certified Core

*Google via Coursera* | 2024 | Foundations of Cybersecurity

*NVIDIA via Coursera* | 2025 | Introduction to Networking

=== Volunteering

.SCaLE AV Team (Current)
- Update existing AV Team Documentation and create new documentation for an internal cutter program used to process livestreams for upload to YouTube. Develop multiple strategies for delivering the information to volunteers before and during the conference.

.DOF (Current)
- Assist in documentation and marketing of DOF projects, starting with YAML Datastore. The DOF team uses a novel docs-as-code approach.

.Open Source Ecology Developer (6 months)
- Document workflows for using a D3D 3D Printer for Pen Plotting using Inkscape and G-code tools.
- Helped edit wiki materials

.BusKill Developer (5 years)
- Spent 4 years developing designing an open source 3D printed magnetic USB release shell in OpenSCAD for the BusKill project. 

=== Talks

*DEFCON33* | 2024 | Demo Lab - Tetra Bio PAPRa

- Discussed my Tetra Bio's project to build a powered air respirator (PAPRa) that uses 3D printing and easily sourceable components. PAPRas deliver pressurized filtered air to the user, defending them from airborn pathogens and particulates while providing a comfortable breathing experience.

*DEFCON32* | 2023 | Demo Lab - Open Hardware Design for BusKill Cord

- Discussed my project to build an open hardware design for BusKill cables that uses 3D printing and easily sourceable components. BusKill cables are hardware Dead Man’s Switches that use USB events to trigger a laptop to lock, shutdown, or self-destruct when the laptop is physically separated from the operator
