ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT] image:https://img.shields.io/badge/View%20on-GitHub-orange[View on GitHub, link=https://github.com/goldfishlaser/tech-writer-resume] image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=https://goldfishlaser.github.io/tech-writer-resume/melanie-allen-resume.pdf]
endif::[]

== Melanie Allen

[%hardbreaks]
404-468-1620
melanienallen@gmail.com

Dynamic communications professional who brings skills in technical writing, information design, instructional design, product marketing, and cross-departmental team collaboration. Proven ability to manage documentation in multiple industries and using analytics to make continuous improvements

=== Skill Summary

[%hardbreaks]
Technical Communication
Product Marketing
Software Documentation
Manufacturing Documentation
Installation Manuals
Version Control
SME Interviews
Research
Remote Team Collaboration
Multimedia Development
Graphic Design
Instructional Design
Human Computer Interaction

.Tool Proficiency
--
Markdown, ASCIIDOC, HTML, CSS, JS, CMS, YAML, GIMP, Inkscape, OpenSCAD, LibreOffice, Adobe Creative Pro, Microsoft Office
--

=== Professional Experience

==== Movius

_March 2020 - March 2025_

.Product Marketing
--
- Managed the MultiLine Help Center
- Wrote blogs using SEO techniques
- Collaborated with product managers on positioning and messaging
- Created sales enablement materials
- Assisted with planning marketing events
--

==== US Tech Solutions

_July 2004 - October 2016_

.Technical Writer | April 2010 – October 2016
--
- Collaborated with the Fiber Education Team to maintain the Customer Service Knowledge Base for Google Fiber
- Scoped change impacts across documentation types.
- Participated in a complete revamping of the organization of our reusable content.
- Bootstrapped the new Sales knowledge base with materials from the CSR knowledge base.
- Used SEO techniques to optimize retrieval of information for techs on the job.
--

=== Education

*Southern Polytechnic State University* | 2012 | B.S. Technical Communication

*Rockdale Magnet School* | 2007 | Graduated with honors
