ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT] image:https://img.shields.io/badge/View%20on-GitHub-orange[View on GitHub, link=https://github.com/goldfishlaser/tech-writer-resume] image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=https://goldfishlaser.github.io/tech-writer-resume/melanie-allen-resume.pdf]
endif::[]

== Melanie Allen

[%hardbreaks]
Technical Content Specialist
404-468-1620
melanienallen@gmail.com

Dynamic communications professional who brings skills in technical writing, information design, instructional design, product marketing, and cross-departmental team collaboration. Proven ability to manage documentation in multiple industries and use analytics to make continuous improvements

=== Skill Summary

[%hardbreaks]
- Technical Communication
- Product Marketing
- Software Documentation
- Manufacturing Documentation
- Installation Manuals
- Version Control
- SME Interviews
- Research
- Remote Team Collaboration
- Multimedia Development
- Graphic Design
- Instructional Design
- Human Computer Interaction

.Tool Proficiency
--
Markdown, ASCIIDOC, HTML, CSS, JS, CMS, YAML, GIMP, Inkscape, OpenSCAD, LibreOffice, Adobe Creative Pro, Microsoft Office
--

=== Professional Experience

==== Movius

.Product Marketing | March 2020 – March 2025
--
- Managed the MultiLine Help Center
- Wrote blogs using SEO techniques
- Collaborated with product managers on positioning and messaging
- Created sales enablement materials
- Assisted with planning marketing events
--

==== US Tech Solutions

.Technical Writer | April 2010 – October 2016
--
- Collaborated with the Fiber Education Team to maintain the Customer Service Knowledge Base for Google Fiber
- Scoped change impacts across documentation types.
- Participated in a complete revamping of the organization of our reusable content.
- Bootstrapped the new Sales knowledge base with materials from the CSR knowledge base.
- Used SEO techniques to optimize retrieval of information for techs on the job.
--

==== TOTO USA

.Technical Writer | April 2010 – October 2016
--
- Managed, edited, and created new installation manuals using InDesign and spare part sheets using Adobe Illustrator for the entire offering of plumbing fixtures and accessories at TOTO USA.
- Interviewed Product Engineers and Tech Support, participated in installation demonstrations, and reviewed existing documentation to gather information to write new installation manuals and spare part sheets with minimal oversight.
- Completed projects on schedule according to the Design Review (DR) and Modification Design Review (MDR) processes.
- Collaborated with the Documentation Specialist and Development Engineering team to complete edits to manuals and spare part sheets according to Engineering Change Notices (ECNs).
- Updated information for spare part sheets for China team in their Microsoft Access database.
- Created a Development Engineering Style Guide to ensure that documents were consistent in style, terminology, and layout.
--

==== Southern Polytechnic State University

.Instructional Designer | Aug 2012 – Aug 2013
--
- Worked on a team creating offline help documentation and material for workshops that taught SPSU faculty how to transition their online and face to face courses to the Desire2Learn LMS system.
- Helped with the development of a new Teaching Academy for Distance Learning course that provided "online teaching concepts, pedagogy, tools training [including GeorgiaVIEW Desire2Learn (D2L), Wimba, Respondus, Turnitin, Ensemble, etc.] and individualized assistance with course development/revision".
--

=== Education

*Southern Polytechnic State University* | 2012 | B.S. Technical Communication

*Rockdale Magnet School* | 2007 | Graduated with honors

=== Certifications

*DeepLearning.Ai via Coursera* | 2019 | Neural Networks and Deep Learning and Coursera

*Product Marketing Alliance* | 2023 | Product Marketing Certified Core

*Google via Coursera* | 2024 | Foundations of Cybersecurity

*NVIDIA via Coursera* | 2025 | Introduction to Networking

=== Volunteering

.Open Source Ecology Developer
- Spent 6 months volunteering to document workflows for using a D3D 3D Printer for Pen Plotting using Inkscape and G-code tools.
- Helped edit wiki materials

.BusKill Developer
- Spent 4 years developing designing an open source 3D printed magnetic USB release shell in OpenSCAD for the BusKill project. 

=== Talks

*DEFCON32* | 2023 | Demo Lab - Open Hardware Design for BusKillCord

- Presented a Demo Lab at Defcon32 discussing my project to build an open hardware design for BusKill cables that uses 3D printing and easily sourceable components. BusKill cables are hardware Dead Man’s Switches that use USB events to trigger a laptop to lock, shutdown, or self-destruct when the laptop is physically separated from the operator
